server {
    listen 80;
    server_name nexusiotenergy.com.br www.nexusiotenergy.com.br;

    root /var/www/nexusiotenergy;
    index index.html;

    access_log /var/log/nginx/nexusiotenergy.access.log;
    error_log /var/log/nginx/nexusiotenergy.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|webp)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
